### ISSUE TITLE
yaml: no quotation; src: same quotation; issues: add auto auther assign

### ISSUE THREAD

**Issue by seunggabi** [toshimaru/auto-author-assign#78]
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

**Comment by seunggabi** [comment]
@toshimaru hello ! please check pr!

**Comment by toshimaru** [comment]
I believe this has been resolved.

**Comment by seunggabi** [comment]
@toshimaru thx man~!
